# **Capstone Project: A Bi-Objective Evolutionary Approach to Feature Selection for Customer Value Prediction in Fintech**

# *Initial Exploratory Data Analysis*

## MBAI 5600G: Applied Integrative Analytics Capstone Project

### Group 7: Brennan Mason & Mohammad Shah
---

## Environment Setup

In [ ]:
# Specify base path to local directory
BASE_PATH = "/content/drive/Shareddrives/MBAI Capstone S S26 Group 7/"

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Data Ingestion & Inspection

In [ ]:
import pandas as pd

# Define path
path = BASE_PATH + "p2p-customer-value-prediction/data/interim/sampled_loans.csv"

# Load data
loans = pd.read_csv(path)

# Inspect head
loans.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,spread,issue_yr_mnth,avg_spread,min_spread,return,beta,disc_rate,loan_duration,avg_monthly_cash_flow,rar
0,49763530,NaN,7000.0,7000.0,7000.0,36 months,0.0789,219.00,A,A5,...,0.077472,2015-05,0.124520,0.051806,0.124084,0.404783,0.006530,32.0,245.893361,7126.312861
1,1614412,NaN,5000.0,5000.0,5000.0,36 months,0.0603,152.18,A,A1,...,0.058818,2012-10,0.137318,0.058518,0.091950,0.404783,0.007239,29.0,188.267241,4944.316301
2,19435976,NaN,10000.0,10000.0,10000.0,36 months,0.0712,309.32,A,A3,...,0.070246,2014-06,0.138971,0.059056,0.113552,0.404783,0.007315,36.0,309.319915,9830.124029
3,44756872,NaN,12000.0,12000.0,12000.0,36 months,0.0593,364.69,A,A1,...,0.057898,2015-04,0.124802,0.057898,0.093717,0.404783,0.006820,36.0,364.572381,11681.851552
4,108855699,NaN,6700.0,6700.0,6700.0,36 months,0.0532,201.77,A,A1,...,0.042755,2017-05,0.126481,0.042755,0.029875,0.404783,0.006173,8.0,862.520378,6753.795702

In [ ]:
# Check size and type of data
loans.info(verbose=True, memory_usage="deep", show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268615 entries, 0 to 268614
Data columns (total 163 columns):
 #    Column                                      Non-Null Count   Dtype
---   ------                                      --------------   -----
 0    id                                          268615 non-null  int64
 1    member_id                                   0 non-null       float64
 2    loan_amnt                                   268615 non-null  float64
 3    funded_amnt                                 268615 non-null  float64
 4    funded_amnt_inv                             268615 non-null  float64
 5    term                                        268615 non-null  object
 6    int_rate                                    268615 non-null  float64
 7    installment                                 268615 non-null  float64
 8    grade                                       268615 non-null  object
 9    sub_grade                                   268615 non-null  object
 10   emp_title                                   251691 non-null  object
 11   emp_length                                  253164 non-null  object
 12   home_ownership                              268615 non-null  object
 13   annual_inc                                  268615 non-null  float64
 14   verification_status                         268615 non-null  object
 15   issue_d                                     268615 non-null  object
 16   loan_status                                 268615 non-null  object
 17   pymnt_plan                                  268615 non-null  object
 18   url                                         268615 non-null  object
 19   desc                                        24631 non-null   object
 20   purpose                                     268615 non-null  object
 21   title                                       265294 non-null  object
 22   zip_code                                    268614 non-null  object
 23   addr_state                                  268615 non-null  object
 24   dti                                         268552 non-null  float64
 25   delinq_2yrs                                 268615 non-null  float64
 26   earliest_cr_line                            268615 non-null  object
 27   fico_range_low                              268615 non-null  float64
 28   fico_range_high                             268615 non-null  float64
 29   inq_last_6mths                              268615 non-null  float64
 30   mths_since_last_delinq                      133144 non-null  float64
 31   mths_since_last_record                      45725 non-null   float64
 32   open_acc                                    268615 non-null  float64
 33   pub_rec                                     268615 non-null  float64
 34   revol_bal                                   268615 non-null  float64
 35   revol_util                                  268447 non-null  float64
 36   total_acc                                   268615 non-null  float64
 37   initial_list_status                         268615 non-null  object
 38   out_prncp                                   268615 non-null  float64
 39   out_prncp_inv                               268615 non-null  float64
 40   total_pymnt                                 268615 non-null  float64
 41   total_pymnt_inv                             268615 non-null  float64
 42   total_rec_prncp                             268615 non-null  float64
 43   total_rec_int                               268615 non-null  float64
 44   total_rec_late_fee                          268615 non-null  float64
 45   recoveries                                  268615 non-null  float64
 46   collection_recovery_fee                     268615 non-null  float64
 47   last_pymnt_d                                268615 non-null  object
 48   last_pymnt_amnt                             268615 non-null  float64
 49   next_pymnt_d                                0 non-null       float64
 50   last_credit_pull_d                          268610 non-null  object
 51   last_fico_range_high                        268615 non-null  float64
 52   last_fico_range_low                         268615 non-null  float64
 53   collections_12_mths_ex_med                  268607 non-null  float64
 54   mths_since_last_major_derog                 70462 non-null   float64
 55   policy_code                                 268615 non-null  float64
 56   application_type                            268615 non-null  object
 57   annual_inc_joint                            5134 non-null    float64
 58   dti_joint                                   5133 non-null    float64
 59   verification_status_joint                   5093 non-null    object
 60   acc_now_delinq                              268615 non-null  float64
 61   tot_coll_amt                                254957 non-null  float64
 62   tot_cur_bal                                 254957 non-null  float64
 63   open_acc_6m                                 107656 non-null  float64
 64   open_act_il                                 107656 non-null  float64
 65   open_il_12m                                 107656 non-null  float64
 66   open_il_24m                                 107656 non-null  float64
 67   mths_since_rcnt_il                          104844 non-null  float64
 68   total_bal_il                                107656 non-null  float64
 69   il_util                                     93169 non-null   float64
 70   open_rv_12m                                 107656 non-null  float64
 71   open_rv_24m                                 107656 non-null  float64
 72   max_bal_bc                                  107656 non-null  float64
 73   all_util                                    107643 non-null  float64
 74   total_rev_hi_lim                            254957 non-null  float64
 75   inq_fi                                      107656 non-null  float64
 76   total_cu_tl                                 107656 non-null  float64
 77   inq_last_12m                                107656 non-null  float64
 78   acc_open_past_24mths                        259028 non-null  float64
 79   avg_cur_bal                                 254952 non-null  float64
 80   bc_open_to_buy                              256225 non-null  float64
 81   bc_util                                     256075 non-null  float64
 82   chargeoff_within_12_mths                    268607 non-null  float64
 83   delinq_amnt                                 268615 non-null  float64
 84   mo_sin_old_il_acct                          247411 non-null  float64
 85   mo_sin_old_rev_tl_op                        254957 non-null  float64
 86   mo_sin_rcnt_rev_tl_op                       254957 non-null  float64
 87   mo_sin_rcnt_tl                              254957 non-null  float64
 88   mort_acc                                    259028 non-null  float64
 89   mths_since_recent_bc                        256420 non-null  float64
 90   mths_since_recent_bc_dlq                    63525 non-null   float64
 91   mths_since_recent_inq                       233688 non-null  float64
 92   mths_since_recent_revol_delinq              89785 non-null   float64
 93   num_accts_ever_120_pd                       254957 non-null  float64
 94   num_actv_bc_tl                              254957 non-null  float64
 95   num_actv_rev_tl                             254957 non-null  float64
 96   num_bc_sats                                 257298 non-null  float64
 97   num_bc_tl                                   254957 non-null  float64
 98   num_il_tl                                   254957 non-null  float64
 99   num_op_rev_tl                               254957 non-null  float64
 100  num_rev_accts                               254956 non-null  float64
 101  num_rev_tl_bal_gt_0                         254957 non-null  float64
 102  num_sats                                    257298 non-null  float64
 103  num_tl_120dpd_2m                            244882 non-null  float64
 104  num_tl_30dpd                                254957 non-null  float64
 105  num_tl_90g_dpd_24m                          254957 non-null  float64
 106  num_tl_op_past_12m                          254957 non-null  float64
 107  pct_tl_nvr_dlq                              254932 non-null  float64
 108  percent_bc_gt_75                            256136 non-null  float64
 109  pub_rec_bankruptcies                        268468 non-null  float64
 110  tax_liens                                   268610 non-null  float64
 111  tot_hi_cred_lim                             254957 non-null  float64
 112  total_bal_ex_mort                           259028 non-null  float64
 113  total_bc_limit                              259028 non-null  float64
 114  total_il_high_credit_limit                  254957 non-null  float64
 115  revol_bal_joint                             3683 non-null    float64
 116  sec_app_fico_range_low                      3683 non-null    float64
 117  sec_app_fico_range_high                     3683 non-null    float64
 118  sec_app_earliest_cr_line                    3683 non-null    object
 119  sec_app_inq_last_6mths                      3683 non-null    float64
 120  sec_app_mort_acc                            3683 non-null    float64
 121  sec_app_open_acc                            3683 non-null    float64
 122  sec_app_revol_util                          3614 non-null    float64
 123  sec_app_open_act_il                         3683 non-null    float64
 124  sec_app_num_rev_accts                       3683 non-null    float64
 125  sec_app_chargeoff_within_12_mths            3683 non-null    float64
 126  sec_app_collections_12_mths_ex_med          3683 non-null    float64
 127  sec_app_mths_since_last_major_derog         1295 non-null    float64
 128  hardship_flag                               268615 non-null  object
 129  hardship_type                               1130 non-null    object
 130  hardship_reason                             1130 non-null    object
 131  hardship_status                             1130 non-null    object
 132  deferral_term                               1130 non-null    float64
 133  hardship_amount                             1130 non-null    float64
 134  hardship_start_date                         1130 non-null    object
 135  hardship_end_date                           1130 non-null    object
 136  payment_plan_start_date                     1130 non-null    object
 137  hardship_length                             1130 non-null    float64
 138  hardship_dpd                                1130 non-null    float64
 139  hardship_loan_status                        1130 non-null    object
 140  orig_projected_additional_accrued_interest  734 non-null     float64
 141  hardship_payoff_balance_amount              1130 non-null    float64
 142  hardship_last_payment_amount                1130 non-null    float64
 143  disbursement_method                         268615 non-null  object
 144  debt_settlement_flag                        268615 non-null  object
 145  debt_settlement_flag_date                   6664 non-null    object
 146  settlement_status                           6664 non-null    object
 147  settlement_date                             6664 non-null    object
 148  settlement_amount                           6664 non-null    float64
 149  settlement_percentage                       6664 non-null    float64
 150  settlement_term                             6664 non-null    float64
 151  issue_yr                                    268615 non-null  int64
 152  avg_cdi_rate                                268615 non-null  float64
 153  spread                                      268615 non-null  float64
 154  issue_yr_mnth                               268615 non-null  object
 155  avg_spread                                  268615 non-null  float64
 156  min_spread                                  268615 non-null  float64
 157  return                                      268615 non-null  float64
 158  beta                                        268615 non-null  float64
 159  disc_rate                                   268615 non-null  float64
 160  loan_duration                               268615 non-null  float64
 161  avg_monthly_cash_flow                       268615 non-null  float64
 162  rar                                         268615 non-null  float64
dtypes: float64(124), int64(2), object(37)
memory usage: 730.9 MB

In [ ]:
# Specify and drop intermediate features used to derive the target variable
cols = [
    "issue_yr",
    "avg_cdi_rate",
    "spread",
    "issue_yr_mnth",
    "avg_spread",
    "min_spread",
    "return",
    "beta",
    "disc_rate",
    "loan_duration",
    "avg_monthly_cash_flow"
]

loans.drop(cols, axis=1, inplace=True)
loans.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268615 entries, 0 to 268614
Columns: 152 entries, id to rar
dtypes: float64(115), int64(1), object(36)
memory usage: 696.0 MB

In [ ]:
from pandas.tseries.offsets import MonthEnd

# Convert issue_d to datetime type
loans["issue_d"] = pd.to_datetime(loans["issue_d"])

# Get date range
start_date = loans["issue_d"].min()
end_date = loans["issue_d"].max() + MonthEnd(0)

# Compute length of reference period in months
ref_period = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month) + 1

# Print results
print("Start Date:", start_date.strftime("%Y-%m-%d"))
print("End Date:", end_date.strftime("%Y-%m-%d"))
print(f"Reference Period Length: {ref_period} months")

Start Date: 2007-07-01
End Date: 2018-12-31
Reference Period Length: 138 months

In [ ]:
# Check for duplicate observations
loans.duplicated().sum()

np.int64(0)

## Missing Value Analysis

In [ ]:
# Define function to identify columns with missingness above a specified threshold
def check_missingness(df, threshold):
  """
  Identifies and returns sparse columns in a provided DataFrame with missingness above a specified threshold.

  Parameters:
  -----------
      - df (pandas.core.frame.DataFrame): DataFrame to analyze.
      - threshold (float): Proportion of missing values above which a column is considered sparse.

  Returns:
  --------
      - dict: Dictionary containing column names as keys and corresponding missingness percentages as values.
  """
  # Get total observation count
  n_obs = len(df)

  # Initialize empty dict to store sparse column names and respective missingness %s
  sparse_cols = {}

  # Iterate through columns
  for col in df.columns:
    # Compute missingness %
    pct_missing = df[col].isna().sum() / n_obs

    # Check if missingness % is above threshold
    if pct_missing > threshold:
      sparse_cols[col] = pct_missing

  # Sort dict desc
  sparse_cols = dict(sorted(sparse_cols.items(), key=lambda x: x[1], reverse=True))

  # Return dict
  return sparse_cols

# Identify and print columns with missingness above 50%
sparse_cols = check_missingness(loans, 0.5)

for i, (col, pct) in enumerate(sparse_cols.items(), start=1):
  print(f"{i}. {col}: {pct:.2%}")

1. member_id: 100.00%
2. next_pymnt_d: 100.00%
3. orig_projected_additional_accrued_interest: 99.73%
4. hardship_type: 99.58%
5. hardship_reason: 99.58%
6. hardship_status: 99.58%
7. deferral_term: 99.58%
8. hardship_amount: 99.58%
9. hardship_start_date: 99.58%
10. hardship_end_date: 99.58%
11. payment_plan_start_date: 99.58%
12. hardship_length: 99.58%
13. hardship_dpd: 99.58%
14. hardship_loan_status: 99.58%
15. hardship_payoff_balance_amount: 99.58%
16. hardship_last_payment_amount: 99.58%
17. sec_app_mths_since_last_major_derog: 99.52%
18. sec_app_revol_util: 98.65%
19. revol_bal_joint: 98.63%
20. sec_app_fico_range_low: 98.63%
21. sec_app_fico_range_high: 98.63%
22. sec_app_earliest_cr_line: 98.63%
23. sec_app_inq_last_6mths: 98.63%
24. sec_app_mort_acc: 98.63%
25. sec_app_open_acc: 98.63%
26. sec_app_open_act_il: 98.63%
27. sec_app_num_rev_accts: 98.63%
28. sec_app_chargeoff_within_12_mths: 98.63%
29. sec_app_collections_12_mths_ex_med: 98.63%
30. verification_status_joint: 98.10%
31. dti_joint: 98.09%
32. annual_inc_joint: 98.09%
33. debt_settlement_flag_date: 97.52%
34. settlement_status: 97.52%
35. settlement_date: 97.52%
36. settlement_amount: 97.52%
37. settlement_percentage: 97.52%
38. settlement_term: 97.52%
39. desc: 90.83%
40. mths_since_last_record: 82.98%
41. mths_since_recent_bc_dlq: 76.35%
42. mths_since_last_major_derog: 73.77%
43. mths_since_recent_revol_delinq: 66.57%
44. il_util: 65.32%
45. mths_since_rcnt_il: 60.97%
46. all_util: 59.93%
47. open_acc_6m: 59.92%
48. open_act_il: 59.92%
49. open_il_12m: 59.92%
50. open_il_24m: 59.92%
51. total_bal_il: 59.92%
52. open_rv_12m: 59.92%
53. open_rv_24m: 59.92%
54. max_bal_bc: 59.92%
55. inq_fi: 59.92%
56. total_cu_tl: 59.92%
57. inq_last_12m: 59.92%
58. mths_since_last_delinq: 50.43%

In [ ]:
# Identify and print columns with any missing values
missing_cols = check_missingness(loans, 0.0)

for i, (col, pct) in enumerate(missing_cols.items(), start=1):
  print(f"{i}. {col}: {pct:.2%}")

1. member_id: 100.00%
2. next_pymnt_d: 100.00%
3. orig_projected_additional_accrued_interest: 99.73%
4. hardship_type: 99.58%
5. hardship_reason: 99.58%
6. hardship_status: 99.58%
7. deferral_term: 99.58%
8. hardship_amount: 99.58%
9. hardship_start_date: 99.58%
10. hardship_end_date: 99.58%
11. payment_plan_start_date: 99.58%
12. hardship_length: 99.58%
13. hardship_dpd: 99.58%
14. hardship_loan_status: 99.58%
15. hardship_payoff_balance_amount: 99.58%
16. hardship_last_payment_amount: 99.58%
17. sec_app_mths_since_last_major_derog: 99.52%
18. sec_app_revol_util: 98.65%
19. revol_bal_joint: 98.63%
20. sec_app_fico_range_low: 98.63%
21. sec_app_fico_range_high: 98.63%
22. sec_app_earliest_cr_line: 98.63%
23. sec_app_inq_last_6mths: 98.63%
24. sec_app_mort_acc: 98.63%
25. sec_app_open_acc: 98.63%
26. sec_app_open_act_il: 98.63%
27. sec_app_num_rev_accts: 98.63%
28. sec_app_chargeoff_within_12_mths: 98.63%
29. sec_app_collections_12_mths_ex_med: 98.63%
30. verification_status_joint: 98.10%
31. dti_joint: 98.09%
32. annual_inc_joint: 98.09%
33. debt_settlement_flag_date: 97.52%
34. settlement_status: 97.52%
35. settlement_date: 97.52%
36. settlement_amount: 97.52%
37. settlement_percentage: 97.52%
38. settlement_term: 97.52%
39. desc: 90.83%
40. mths_since_last_record: 82.98%
41. mths_since_recent_bc_dlq: 76.35%
42. mths_since_last_major_derog: 73.77%
43. mths_since_recent_revol_delinq: 66.57%
44. il_util: 65.32%
45. mths_since_rcnt_il: 60.97%
46. all_util: 59.93%
47. open_acc_6m: 59.92%
48. open_act_il: 59.92%
49. open_il_12m: 59.92%
50. open_il_24m: 59.92%
51. total_bal_il: 59.92%
52. open_rv_12m: 59.92%
53. open_rv_24m: 59.92%
54. max_bal_bc: 59.92%
55. inq_fi: 59.92%
56. total_cu_tl: 59.92%
57. inq_last_12m: 59.92%
58. mths_since_last_delinq: 50.43%
59. mths_since_recent_inq: 13.00%
60. num_tl_120dpd_2m: 8.84%
61. mo_sin_old_il_acct: 7.89%
62. emp_title: 6.30%
63. emp_length: 5.75%
64. pct_tl_nvr_dlq: 5.09%
65. avg_cur_bal: 5.09%
66. num_rev_accts: 5.08%
67. tot_coll_amt: 5.08%
68. tot_cur_bal: 5.08%
69. total_rev_hi_lim: 5.08%
70. mo_sin_old_rev_tl_op: 5.08%
71. mo_sin_rcnt_rev_tl_op: 5.08%
72. mo_sin_rcnt_tl: 5.08%
73. num_accts_ever_120_pd: 5.08%
74. num_actv_bc_tl: 5.08%
75. num_actv_rev_tl: 5.08%
76. num_bc_tl: 5.08%
77. num_il_tl: 5.08%
78. num_op_rev_tl: 5.08%
79. num_rev_tl_bal_gt_0: 5.08%
80. num_tl_30dpd: 5.08%
81. num_tl_90g_dpd_24m: 5.08%
82. num_tl_op_past_12m: 5.08%
83. tot_hi_cred_lim: 5.08%
84. total_il_high_credit_limit: 5.08%
85. bc_util: 4.67%
86. percent_bc_gt_75: 4.65%
87. bc_open_to_buy: 4.61%
88. mths_since_recent_bc: 4.54%
89. num_bc_sats: 4.21%
90. num_sats: 4.21%
91. acc_open_past_24mths: 3.57%
92. mort_acc: 3.57%
93. total_bal_ex_mort: 3.57%
94. total_bc_limit: 3.57%
95. title: 1.24%
96. revol_util: 0.06%
97. pub_rec_bankruptcies: 0.05%
98. dti: 0.02%
99. collections_12_mths_ex_med: 0.00%
100. chargeoff_within_12_mths: 0.00%
101. last_credit_pull_d: 0.00%
102. tax_liens: 0.00%
103. zip_code: 0.00%

In [ ]:
# Construct binned missingness summary table
missing_df = loans.isna().sum().reset_index()
missing_df.rename(columns={"index": "variable", 0: "missing_count"}, inplace=True)
missing_df["missing_pct"] = missing_df["missing_count"] / len(loans)

missing_df["missing_bin"] = pd.cut(
    missing_df["missing_pct"],
    bins=[0, (1 / len(loans)), 0.1301, 1.01],
    right=False,
    include_lowest=True,
    labels=["None", "Low", "High"]
)

missing_summary = missing_df.value_counts("missing_bin").sort_index(ascending=False).reset_index()
missing_summary.rename(columns={0: "variable_count"}, inplace=True)

missing_summary

  missing_bin  count
0        High     58
1         Low     45
2        None     49

## Distribution Analysis

In [ ]:
import plotly.graph_objects as go

# Visualize RAR distribution
fig = go.Figure()

fig.add_trace(go.Histogram(
    x=loans["rar"],
    nbinsx=40,
    marker=dict(color="steelblue"),
    name="RAR"
))

fig.update_layout(
    title="Distribution of Risk-Adjusted Revenue",
    xaxis_title="Risk-Adjusted Revenue ($)",
    yaxis_title="Frequency",
    template="seaborn",
    font=dict(
        family="Helvetica Neue, sans-serif",
        color="#666666"
    ),
    width=1000,
    height=600
)

fig.update_yaxes(ticklabelstandoff=5)
fig.update_xaxes(ticklabelstandoff=5)

fig.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# Get list of numeric columns
num_cols = loans.select_dtypes(include="number").columns.tolist()

In [ ]:
# Define function to identify numeric columns with skewness above a specified threshold
def check_skewness(df, cols, threshold=0.5):
  """
  Identifies and returns skewed numeric columns in a provided DataFrame with skewness above a specified threshold.

  Parameters:
  -----------
      - df (pandas.core.frame.DataFrame): DataFrame to analyze.
      - cols (list): List of numeric column names to analyze.
      - threshold (float): Absolute skewness value above which a column is considered skewed. Default is 0.5.

  Returns:
  --------
      - dict: Dictionary containing column names as keys and corresponding skewness values as values.
  """
  # Get subset of relevant (i.e., numeric) columns
  df = df[cols]

  # Initialize empty dict to store skewed column names and respective skewness
  skewed_cols = {}

  # Iterate through columns
  for col in df.columns:
    # Compute skewness
    skew = df[col].skew()

    # Check if absolute skewness is above threshold
    if abs(skew) > threshold:
      skewed_cols[col] = skew

  # Sort dict desc
  skewed_cols = dict(sorted(skewed_cols.items(), key=lambda x: abs(x[1]), reverse=True))

  # Return dict
  return skewed_cols

# Identify and print columns with skewed distributions
skewed_cols = check_skewness(loans, num_cols, threshold=0.5)

for i, (col, skew) in enumerate(skewed_cols.items(), start=1):
  print(f"{i}. {col}: {skew:.2f}")

1. tot_coll_amt: 147.17
2. delinq_amnt: 83.75
3. tax_liens: 51.50
4. num_tl_120dpd_2m: 38.08
5. dti: 31.11
6. annual_inc: 28.94
7. max_bal_bc: 26.16
8. sec_app_chargeoff_within_12_mths: 24.14
9. collections_12_mths_ex_med: 21.99
10. chargeoff_within_12_mths: 20.08
11. num_tl_30dpd: 19.32
12. pub_rec: 18.69
13. total_rec_late_fee: 16.87
14. acc_now_delinq: 15.95
15. num_tl_90g_dpd_24m: 13.37
16. revol_bal: 10.42
17. collection_recovery_fee: 8.87
18. sec_app_collections_12_mths_ex_med: 8.76
19. recoveries: 8.21
20. total_rev_hi_lim: 6.50
21. delinq_2yrs: 5.63
22. num_accts_ever_120_pd: 5.00
23. mo_sin_rcnt_tl: 4.48
24. avg_cur_bal: 3.88
25. total_bal_il: 3.84
26. bc_open_to_buy: 3.81
27. total_bal_ex_mort: 3.68
28. mths_since_rcnt_il: 3.53
29. mths_since_recent_bc: 3.47
30. mo_sin_rcnt_rev_tl_op: 3.44
31. pub_rec_bankruptcies: 3.38
32. total_bc_limit: 3.32
33. total_cu_tl: 3.31
34. total_il_high_credit_limit: 3.29
35. last_fico_range_low: -3.24
36. tot_hi_cred_lim: 3.19
37. sec_app_open_act_il: 3.16
38. open_act_il: 3.10
39. tot_cur_bal: 2.85
40. inq_fi: 2.69
41. total_rec_int: 2.63
42. annual_inc_joint: 2.48
43. inq_last_12m: 2.33
44. revol_bal_joint: 2.29
45. pct_tl_nvr_dlq: -2.23
46. open_rv_12m: 2.06
47. num_il_tl: 2.06
48. open_rv_24m: 1.93
49. sec_app_inq_last_6mths: 1.82
50. last_pymnt_amnt: 1.78
51. hardship_last_payment_amount: 1.78
52. open_il_24m: 1.76
53. open_il_12m: 1.74
54. settlement_percentage: 1.73
55. hardship_amount: 1.73
56. num_bc_sats: 1.71
57. inq_last_6mths: 1.70
58. open_acc_6m: 1.63
59. mort_acc: 1.62
60. orig_projected_additional_accrued_interest: 1.56
61. num_actv_rev_tl: 1.54
62. num_tl_op_past_12m: 1.53
63. sec_app_num_rev_accts: 1.51
64. num_op_rev_tl: 1.46
65. sec_app_mort_acc: 1.46
66. sec_app_open_acc: 1.44
67. num_rev_tl_bal_gt_0: 1.44
68. num_actv_bc_tl: 1.40
69. acc_open_past_24mths: 1.38
70. num_bc_tl: 1.35
71. num_rev_accts: 1.31
72. num_sats: 1.31
73. open_acc: 1.31
74. fico_range_high: 1.29
75. fico_range_low: 1.29
76. settlement_amount: 1.27
77. mo_sin_old_rev_tl_op: 1.04
78. total_pymnt: 1.04
79. total_pymnt_inv: 1.04
80. installment: 1.00
81. rar: 0.97
82. hardship_payoff_balance_amount: 0.97
83. total_acc: 0.96
84. mths_since_recent_inq: 0.96
85. total_rec_prncp: 0.91
86. funded_amnt: 0.78
87. funded_amnt_inv: 0.78
88. loan_amnt: 0.78
89. int_rate: 0.71
90. last_fico_range_high: -0.60

In [ ]:
loans["tot_coll_amt"].describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.80, 0.85, 0.90, 0.95])

count    254957.000000
mean        236.317465
std        2659.740621
min           0.000000
5%            0.000000
25%           0.000000
50%           0.000000
75%           0.000000
80%           0.000000
85%          50.000000
90%         207.000000
95%         772.000000
max      848438.000000
Name: tot_coll_amt, dtype: float64

## Outlier Analysis

In [ ]:
# Define function to identify numeric columns with outliers
def id_outliers(df, cols, iqr_multiplier=1.5, z_threshold=3.0):
  """
  Identifies and returns numeric columns in a provided DataFrame containing outliers.
  Outliers are identified using either the IQR method or the Z-score method based on skewness.

  Parameters:
  -----------
      - df (pandas.core.frame.DataFrame): DataFrame to analyze.
      - cols (list): List of numeric column names to analyze.
      - iqr_multiplier (float): Multiplier for the IQR method. Default is 1.5.
      - z_threshold (float): Threshold for the Z-score method. Default is 3.0.

  Returns:
  --------
      - dict: Dictionary containing column names as keys and corresponding outlier counts as values.
  """
  # Get subset of relevant (i.e., numeric) columns
  df = df[cols]

  # Initialize empty dict to store names of columns with outliers and respective outlier counts
  outlier_cols = {}

  # Iterate through columns
  for col in df.columns:
    # Compute skewness
    skew = df[col].skew()

    # Assess skewness to determine appropriate outlier detection method
    if abs(skew) > 0.5:
      # Use IQR method
      # Compute Q1 and Q3
      q1 = df[col].quantile(0.25)
      q3 = df[col].quantile(0.75)

      # Compute IQR
      iqr = q3 - q1

      # Compute upper and lower fences
      uf = q3 + (iqr_multiplier * iqr)
      lf = q1 - (iqr_multiplier * iqr)

      # Detect outliers
      outlier_mask = (df[col] > uf) | (df[col] < lf)

    else:
      # Use Z-score method
      # Compute Z-scores (i.e., standardize observations)
      z_scores = (df[col] - df[col].mean()) / df[col].std()

      # Detect outliers
      outlier_mask = z_scores.abs() > z_threshold

    # Count outliers
    n_outliers = outlier_mask.sum()

    # Check if any outliers
    if n_outliers > 0:
      outlier_cols[col] = n_outliers

  # Sort dict desc
  outlier_cols = dict(sorted(outlier_cols.items(), key=lambda x: x[1], reverse=True))

  # Return dict
  return outlier_cols

# Identify and print columns containing outliers
outlier_cols = id_outliers(loans, num_cols, iqr_multiplier=1.5, z_threshold=3.0)

for i, (col, n_outliers) in enumerate(outlier_cols.items(), start=1):
  print(f"{i}. {col}: {n_outliers}")

1. num_accts_ever_120_pd: 60338
2. delinq_2yrs: 51635
3. pub_rec: 45582
4. tot_coll_amt: 39017
5. recoveries: 36869
6. collection_recovery_fee: 35140
7. pub_rec_bankruptcies: 33647
8. mths_since_recent_bc: 23983
9. bc_open_to_buy: 22369
10. total_rec_int: 19646
11. mo_sin_rcnt_rev_tl_op: 19547
12. pct_tl_nvr_dlq: 16460
13. revol_bal: 15951
14. total_bc_limit: 15685
15. num_il_tl: 15499
16. total_bal_ex_mort: 15314
17. mo_sin_rcnt_tl: 15310
18. total_rev_hi_lim: 14807
19. last_pymnt_amnt: 14687
20. num_tl_90g_dpd_24m: 14506
21. inq_last_6mths: 14383
22. open_il_24m: 13708
23. avg_cur_bal: 13573
24. annual_inc: 13450
25. total_il_high_credit_limit: 12964
26. total_rec_late_fee: 12028
27. num_bc_sats: 11507
28. num_op_rev_tl: 10698
29. fico_range_low: 9197
30. fico_range_high: 9197
31. open_acc: 9171
32. mths_since_rcnt_il: 9037
33. num_sats: 8940
34. total_cu_tl: 8910
35. open_act_il: 8820
36. tot_cur_bal: 8786
37. tot_hi_cred_lim: 8734
38. tax_liens: 8692
39. installment: 8379
40. mo_sin_old_rev_tl_op: 7433
41. num_actv_rev_tl: 7206
42. last_fico_range_low: 7075
43. num_tl_op_past_12m: 6978
44. inq_last_12m: 6953
45. total_bal_il: 6597
46. num_rev_tl_bal_gt_0: 6489
47. max_bal_bc: 6459
48. num_rev_accts: 6330
49. open_il_12m: 6273
50. total_pymnt_inv: 6019
51. total_pymnt: 6017
52. acc_open_past_24mths: 5991
53. rar: 5602
54. num_actv_bc_tl: 5361
55. num_bc_tl: 5350
56. int_rate: 4944
57. open_rv_24m: 4529
58. total_acc: 4376
59. collections_12_mths_ex_med: 4207
60. mort_acc: 3578
61. mths_since_recent_inq: 2967
62. open_rv_12m: 2509
63. inq_fi: 2483
64. chargeoff_within_12_mths: 2185
65. mo_sin_old_il_acct: 1899
66. loan_amnt: 1429
67. funded_amnt: 1429
68. funded_amnt_inv: 1427
69. acc_now_delinq: 1305
70. total_rec_prncp: 1231
71. dti: 1107
72. delinq_amnt: 1029
73. num_tl_30dpd: 869
74. il_util: 830
75. settlement_percentage: 752
76. open_acc_6m: 746
77. sec_app_inq_last_6mths: 259
78. sec_app_collections_12_mths_ex_med: 216
79. sec_app_open_act_il: 210
80. settlement_amount: 199
81. annual_inc_joint: 185
82. num_tl_120dpd_2m: 185
83. revol_bal_joint: 182
84. all_util: 130
85. sec_app_num_rev_accts: 114
86. sec_app_chargeoff_within_12_mths: 114
87. mths_since_recent_revol_delinq: 109
88. sec_app_open_acc: 99
89. mths_since_last_major_derog: 96
90. mths_since_last_delinq: 78
91. mths_since_recent_bc_dlq: 60
92. hardship_amount: 53
93. hardship_last_payment_amount: 51
94. last_fico_range_high: 41
95. orig_projected_additional_accrued_interest: 34
96. sec_app_mort_acc: 26
97. revol_util: 20
98. bc_util: 18
99. hardship_payoff_balance_amount: 18
100. sec_app_fico_range_low: 11
101. sec_app_fico_range_high: 11
102. dti_joint: 6
103. sec_app_revol_util: 4
104. sec_app_mths_since_last_major_derog: 2
105. settlement_term: 1

In [ ]:
import plotly.express as px

# Visualize Number of Accounts Ever 120+ Days Past Due distribution
fig = px.histogram(
    loans,
    x="num_accts_ever_120_pd",
    log_y=True, # This is the magic parameter
    title="Distribution of Number of Accounts Ever 120+ Days Past Due",
    template="seaborn",
    color_discrete_sequence=["steelblue"]
)

fig.update_layout(
    font=dict(family="Helvetica Neue, sans-serif", color="#666666"),
    xaxis_title="Number of Accounts",
    yaxis_title="Count of Borrowers (Log Scale)",
    width=1000,
    height=600
)

fig.update_yaxes(ticklabelstandoff=5, dtick=1)
fig.update_xaxes(ticklabelstandoff=5)

fig.show()

In [ ]:
loans["num_accts_ever_120_pd"].describe(percentiles=[0.25, 0.50, 0.75, 0.8, 0.85, 0.9, 0.95])

count    254957.000000
mean          0.506050
std           1.313531
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
80%           1.000000
85%           1.000000
90%           2.000000
95%           3.000000
max          33.000000
Name: num_accts_ever_120_pd, dtype: float64

In [ ]:
# Get top 10 features most correlated with target
corr_matrix = loans.corr(numeric_only=True)
corr_cols = corr_matrix.drop(index=["rar"]).abs().nlargest(10, "rar")["rar"].index.to_list()
corr_cols

['total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'funded_amnt',
 'loan_amnt',
 'funded_amnt_inv',
 'installment',
 'last_pymnt_amnt',
 'total_rec_int',
 'settlement_amount']

In [ ]:
from plotly.subplots import make_subplots

# Select top 6 nonredundant features
top_corr_cols = ["total_pymnt", "funded_amnt", "installment", "last_pymnt_amnt", "total_rec_int", "settlement_amount"]

# Construct boxplots to visualize feature distributions and outliers
fig = make_subplots(rows=2, cols=3, subplot_titles=top_corr_cols)

for i, col_name in enumerate(top_corr_cols):
  row = (i // 3) + 1
  col = (i % 3) + 1

  trace = go.Box(
      y=loans[col_name],
      marker_color="steelblue"
  )

  fig.add_trace(trace, row, col)

fig.update_layout(
    title="Distributions of Top 6 Features by Target Correlation",
    template="seaborn",
    showlegend=False,
    font=dict(
        family="Helvetica Neue, sans-serif",
        color="#666666"
    ),
    width=1000,
    height=600
)

fig.update_yaxes(ticklabelstandoff=5)
fig.update_xaxes(showticklabels=False)

fig.show()

Output hidden; open in https://colab.research.google.com to view.

## Variable Descriptions

In [ ]:
# Define path
path = BASE_PATH + "p2p-customer-value-prediction/references/data_dictionary.csv"

# Load data dictionary
data_dict = pd.read_csv(path)

# Strip whitespace from variable names and descriptions
data_dict["LoanStatNew"] = data_dict["LoanStatNew"].str.strip()
data_dict["Description"] = data_dict["Description"].str.strip()

for col in loans.columns:
  # Get variable description
  try:
    desc = data_dict.loc[data_dict["LoanStatNew"] == col, "Description"].values[0]
  except IndexError:
    desc = "N/A"

  # Append period if required
  if desc[-1] not in [".", "*"]:
    desc += "."

  # Get data type
  dtype = loans[col].dtype

  # Print clean list of variable names, types, and descriptions with markdown-friendly formatting
  print(f"* **{col} (*{dtype}*):** {desc}")

* **id (*int64*):** A unique LC assigned ID for the loan listing.
* **member_id (*float64*):** A unique LC assigned Id for the borrower member.
* **loan_amnt (*float64*):** The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.
* **funded_amnt (*float64*):** The total amount committed to that loan at that point in time.
* **funded_amnt_inv (*float64*):** The total amount committed by investors for that loan at that point in time.
* **term (*object*):** The number of payments on the loan. Values are in months and can be either 36 or 60.
* **int_rate (*float64*):** Interest Rate on the loan.
* **installment (*float64*):** The monthly payment owed by the borrower if the loan originates.
* **grade (*object*):** LC assigned loan grade.
* **sub_grade (*object*):** LC assigned loan subgrade.
* **emp_title (*object*):** The job title supplied by the Borrower when applying for the loan.*
* **emp_length (*object*):** Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
* **home_ownership (*object*):** The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER.
* **annual_inc (*float64*):** The self-reported annual income provided by the borrower during registration.
* **verification_status (*object*):** Indicates if income was verified by LC, not verified, or if the income source was verified.
* **issue_d (*datetime64[ns]*):** The month which the loan was funded.
* **loan_status (*object*):** Current status of the loan.
* **pymnt_plan (*object*):** Indicates if a payment plan has been put in place for the loan.
* **url (*object*):** URL for the LC page with listing data.
* **desc (*object*):** Loan description provided by the borrower.
* **purpose (*object*):** A category provided by the borrower for the loan request.
* **title (*object*):** The loan title provided by the borrower.
* **zip_code (*object*):** The first 3 numbers of the zip code provided by the borrower in the loan application.
* **addr_state (*object*):** The state provided by the borrower in the loan application.
* **dti (*float64*):** A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.
* **delinq_2yrs (*float64*):** The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years.
* **earliest_cr_line (*object*):** The month the borrower's earliest reported credit line was opened.
* **fico_range_low (*float64*):** The lower boundary range the borrower’s FICO at loan origination belongs to.
* **fico_range_high (*float64*):** The upper boundary range the borrower’s FICO at loan origination belongs to.
* **inq_last_6mths (*float64*):** The number of inquiries in past 6 months (excluding auto and mortgage inquiries).
* **mths_since_last_delinq (*float64*):** The number of months since the borrower's last delinquency.
* **mths_since_last_record (*float64*):** The number of months since the last public record.
* **open_acc (*float64*):** The number of open credit lines in the borrower's credit file.
* **pub_rec (*float64*):** Number of derogatory public records.
* **revol_bal (*float64*):** Total credit revolving balance.
* **revol_util (*float64*):** Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.
* **total_acc (*float64*):** The total number of credit lines currently in the borrower's credit file.
* **initial_list_status (*object*):** The initial listing status of the loan. Possible values are – W, F.
* **out_prncp (*float64*):** Remaining outstanding principal for total amount funded.
* **out_prncp_inv (*float64*):** Remaining outstanding principal for portion of total amount funded by investors.
* **total_pymnt (*float64*):** Payments received to date for total amount funded.
* **total_pymnt_inv (*float64*):** Payments received to date for portion of total amount funded by investors.
* **total_rec_prncp (*float64*):** Principal received to date.
* **total_rec_int (*float64*):** Interest received to date.
* **total_rec_late_fee (*float64*):** Late fees received to date.
* **recoveries (*float64*):** post charge off gross recovery.
* **collection_recovery_fee (*float64*):** post charge off collection fee.
* **last_pymnt_d (*object*):** Last month payment was received.
* **last_pymnt_amnt (*float64*):** Last total payment amount received.
* **next_pymnt_d (*float64*):** Next scheduled payment date.
* **last_credit_pull_d (*object*):** The most recent month LC pulled credit for this loan.
* **last_fico_range_high (*float64*):** The upper boundary range the borrower’s last FICO pulled belongs to.
* **last_fico_range_low (*float64*):** The lower boundary range the borrower’s last FICO pulled belongs to.
* **collections_12_mths_ex_med (*float64*):** Number of collections in 12 months excluding medical collections.
* **mths_since_last_major_derog (*float64*):** Months since most recent 90-day or worse rating.
* **policy_code (*float64*):** publicly available policy_code=1
new products not publicly available policy_code=2.
* **application_type (*object*):** Indicates whether the loan is an individual application or a joint application with two co-borrowers.
* **annual_inc_joint (*float64*):** The combined self-reported annual income provided by the co-borrowers during registration.
* **dti_joint (*float64*):** A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported monthly income.
* **verification_status_joint (*object*):** N/A.
* **acc_now_delinq (*float64*):** The number of accounts on which the borrower is now delinquent.
* **tot_coll_amt (*float64*):** Total collection amounts ever owed.
* **tot_cur_bal (*float64*):** Total current balance of all accounts.
* **open_acc_6m (*float64*):** Number of open trades in last 6 months.
* **open_act_il (*float64*):** Number of currently active installment trades.
* **open_il_12m (*float64*):** Number of installment accounts opened in past 12 months.
* **open_il_24m (*float64*):** Number of installment accounts opened in past 24 months.
* **mths_since_rcnt_il (*float64*):** Months since most recent installment accounts opened.
* **total_bal_il (*float64*):** Total current balance of all installment accounts.
* **il_util (*float64*):** Ratio of total current balance to high credit/credit limit on all install acct.
* **open_rv_12m (*float64*):** Number of revolving trades opened in past 12 months.
* **open_rv_24m (*float64*):** Number of revolving trades opened in past 24 months.
* **max_bal_bc (*float64*):** Maximum current balance owed on all revolving accounts.
* **all_util (*float64*):** Balance to credit limit on all trades.
* **total_rev_hi_lim (*float64*):** Total revolving high credit/credit limit.
* **inq_fi (*float64*):** Number of personal finance inquiries.
* **total_cu_tl (*float64*):** Number of finance trades.
* **inq_last_12m (*float64*):** Number of credit inquiries in past 12 months.
* **acc_open_past_24mths (*float64*):** Number of trades opened in past 24 months.
* **avg_cur_bal (*float64*):** Average current balance of all accounts.
* **bc_open_to_buy (*float64*):** Total open to buy on revolving bankcards.
* **bc_util (*float64*):** Ratio of total current balance to high credit/credit limit for all bankcard accounts.
* **chargeoff_within_12_mths (*float64*):** Number of charge-offs within 12 months.
* **delinq_amnt (*float64*):** The past-due amount owed for the accounts on which the borrower is now delinquent.
* **mo_sin_old_il_acct (*float64*):** Months since oldest bank installment account opened.
* **mo_sin_old_rev_tl_op (*float64*):** Months since oldest revolving account opened.
* **mo_sin_rcnt_rev_tl_op (*float64*):** Months since most recent revolving account opened.
* **mo_sin_rcnt_tl (*float64*):** Months since most recent account opened.
* **mort_acc (*float64*):** Number of mortgage accounts.
* **mths_since_recent_bc (*float64*):** Months since most recent bankcard account opened.
* **mths_since_recent_bc_dlq (*float64*):** Months since most recent bankcard delinquency.
* **mths_since_recent_inq (*float64*):** Months since most recent inquiry.
* **mths_since_recent_revol_delinq (*float64*):** Months since most recent revolving delinquency.
* **num_accts_ever_120_pd (*float64*):** Number of accounts ever 120 or more days past due.
* **num_actv_bc_tl (*float64*):** Number of currently active bankcard accounts.
* **num_actv_rev_tl (*float64*):** Number of currently active revolving trades.
* **num_bc_sats (*float64*):** Number of satisfactory bankcard accounts.
* **num_bc_tl (*float64*):** Number of bankcard accounts.
* **num_il_tl (*float64*):** Number of installment accounts.
* **num_op_rev_tl (*float64*):** Number of open revolving accounts.
* **num_rev_accts (*float64*):** Number of revolving accounts.
* **num_rev_tl_bal_gt_0 (*float64*):** Number of revolving trades with balance >0.
* **num_sats (*float64*):** Number of satisfactory accounts.
* **num_tl_120dpd_2m (*float64*):** Number of accounts currently 120 days past due (updated in past 2 months).
* **num_tl_30dpd (*float64*):** Number of accounts currently 30 days past due (updated in past 2 months).
* **num_tl_90g_dpd_24m (*float64*):** Number of accounts 90 or more days past due in last 24 months.
* **num_tl_op_past_12m (*float64*):** Number of accounts opened in past 12 months.
* **pct_tl_nvr_dlq (*float64*):** Percent of trades never delinquent.
* **percent_bc_gt_75 (*float64*):** Percentage of all bankcard accounts > 75% of limit.
* **pub_rec_bankruptcies (*float64*):** Number of public record bankruptcies.
* **tax_liens (*float64*):** Number of tax liens.
* **tot_hi_cred_lim (*float64*):** Total high credit/credit limit.
* **total_bal_ex_mort (*float64*):** Total credit balance excluding mortgage.
* **total_bc_limit (*float64*):** Total bankcard high credit/credit limit.
* **total_il_high_credit_limit (*float64*):** Total installment high credit/credit limit.
* **revol_bal_joint (*float64*):** Sum of revolving credit balance of the co-borrowers, net of duplicate balances.
* **sec_app_fico_range_low (*float64*):** FICO range (high) for the secondary applicant.
* **sec_app_fico_range_high (*float64*):** FICO range (low) for the secondary applicant.
* **sec_app_earliest_cr_line (*object*):** Earliest credit line at time of application for the secondary applicant.
* **sec_app_inq_last_6mths (*float64*):** Credit inquiries in the last 6 months at time of application for the secondary applicant.
* **sec_app_mort_acc (*float64*):** Number of mortgage accounts at time of application for the secondary applicant.
* **sec_app_open_acc (*float64*):** Number of open trades at time of application for the secondary applicant.
* **sec_app_revol_util (*float64*):** Ratio of total current balance to high credit/credit limit for all revolving accounts.
* **sec_app_open_act_il (*float64*):** Number of currently active installment trades at time of application for the secondary applicant.
* **sec_app_num_rev_accts (*float64*):** Number of revolving accounts at time of application for the secondary applicant.
* **sec_app_chargeoff_within_12_mths (*float64*):** Number of charge-offs within last 12 months at time of application for the secondary applicant.
* **sec_app_collections_12_mths_ex_med (*float64*):** Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant.
* **sec_app_mths_since_last_major_derog (*float64*):** Months since most recent 90-day or worse rating at time of application for the secondary applicant.
* **hardship_flag (*object*):** Flags whether or not the borrower is on a hardship plan.
* **hardship_type (*object*):** Describes the hardship plan offering.
* **hardship_reason (*object*):** Describes the reason the hardship plan was offered.
* **hardship_status (*object*):** Describes if the hardship plan is active, pending, canceled, completed, or broken.
* **deferral_term (*float64*):** Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan.
* **hardship_amount (*float64*):** The interest payment that the borrower has committed to make each month while they are on a hardship plan.
* **hardship_start_date (*object*):** The start date of the hardship plan period.
* **hardship_end_date (*object*):** The end date of the hardship plan period.
* **payment_plan_start_date (*object*):** The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is allowed to make interest-only payments.
* **hardship_length (*float64*):** The number of months the borrower will make smaller payments than normally obligated due to a hardship plan.
* **hardship_dpd (*float64*):** Account days past due as of the hardship plan start date.
* **hardship_loan_status (*object*):** Loan Status as of the hardship plan start date.
* **orig_projected_additional_accrued_interest (*float64*):** The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hardship payment plan.
* **hardship_payoff_balance_amount (*float64*):** The payoff balance amount as of the hardship plan start date.
* **hardship_last_payment_amount (*float64*):** The last payment amount as of the hardship plan start date.
* **disbursement_method (*object*):** The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY.
* **debt_settlement_flag (*object*):** Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company.
* **debt_settlement_flag_date (*object*):** The most recent date that the Debt_Settlement_Flag has been set.
* **settlement_status (*object*):** The status of the borrower’s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT.
* **settlement_date (*object*):** The date that the borrower agrees to the settlement plan.
* **settlement_amount (*float64*):** The loan amount that the borrower has agreed to settle for.
* **settlement_percentage (*float64*):** The settlement amount as a percentage of the payoff balance amount on the loan.
* **settlement_term (*float64*):** The number of months that the borrower will be on the settlement plan.
* **rar (*float64*):** N/A.

## Categorical Exploration

In [ ]:
loans["emp_title"].value_counts().nlargest(50)

emp_title
Teacher                     4237
Manager                     3998
Owner                       2099
Registered Nurse            1727
RN                          1705
Supervisor                  1676
Driver                      1508
Sales                       1504
Project Manager             1276
Office Manager              1103
General Manager             1044
Director                    1006
owner                        905
manager                      884
teacher                      859
Engineer                     851
President                    771
Vice President               750
driver                       703
Operations Manager           690
Accountant                   645
Sales Manager                620
Administrative Assistant     617
Attorney                     598
Account Manager              547
Police Officer               530
Technician                   517
Nurse                        509
Analyst                      497
Truck Driver                 486
Executive Assistant          483
sales                        478
Store Manager                458
supervisor                   439
Software Engineer            428
Paralegal                    428
Server                       400
Controller                   390
Consultant                   390
truck driver                 372
Branch Manager               371
Mechanic                     367
Program Manager              363
Foreman                      345
Assistant Manager            340
Business Analyst             336
Electrician                  335
CEO                          332
Account Executive            330
Administrator                328
Name: count, dtype: int64

In [ ]:
cat_cols = loans.select_dtypes(include="object").columns.tolist()

for col in cat_cols:
  print(loans[col].value_counts().nlargest(50))
  print()

term
36 months    203821
60 months     64794
Name: count, dtype: int64

grade
B    78471
C    76219
A    46988
D    40091
E    18650
F     6385
G     1811
Name: count, dtype: int64

sub_grade
C1    17001
B4    16717
B5    16396
B3    16317
C2    15747
C3    15066
B2    14941
C4    14853
B1    14100
C5    13552
A5    12747
A4    10496
D1    10335
D2     8967
A1     8594
D3     7778
A3     7663
A2     7488
D4     7019
D5     5992
E1     4796
E2     4209
E3     3634
E4     3107
E5     2904
F1     1982
F2     1470
F3     1180
F4      984
F5      769
G1      599
G2      431
G3      317
G4      239
G5      225
Name: count, dtype: int64

emp_title
Teacher                     4237
Manager                     3998
Owner                       2099
Registered Nurse            1727
RN                          1705
Supervisor                  1676
Driver                      1508
Sales                       1504
Project Manager             1276
Office Manager              1103
General Manager             1044
Director                    1006
owner                        905
manager                      884
teacher                      859
Engineer                     851
President                    771
Vice President               750
driver                       703
Operations Manager           690
Accountant                   645
Sales Manager                620
Administrative Assistant     617
Attorney                     598
Account Manager              547
Police Officer               530
Technician                   517
Nurse                        509
Analyst                      497
Truck Driver                 486
Executive Assistant          483
sales                        478
Store Manager                458
supervisor                   439
Software Engineer            428
Paralegal                    428
Server                       400
Controller                   390
Consultant                   390
truck driver                 372
Branch Manager               371
Mechanic                     367
Program Manager              363
Foreman                      345
Assistant Manager            340
Business Analyst             336
Electrician                  335
CEO                          332
Account Executive            330
Administrator                328
Name: count, dtype: int64

emp_length
10+ years    88693
2 years      24468
< 1 year     21537
3 years      21423
1 year       17687
5 years      16763
4 years      16103
6 years      12312
8 years      12100
7 years      11923
9 years      10155
Name: count, dtype: int64

home_ownership
MORTGAGE    132736
RENT        106653
OWN          29137
ANY             52
OTHER           26
NONE            11
Name: count, dtype: int64

verification_status
Source Verified    104099
Verified            83590
Not Verified        80926
Name: count, dtype: int64

loan_status
Fully Paid     215249
Charged Off     53366
Name: count, dtype: int64

pymnt_plan
n    268615
Name: count, dtype: int64

url
https://lendingclub.com/browse/loanDetail.action?loan_id=132899040    1
https://lendingclub.com/browse/loanDetail.action?loan_id=49763530     1
https://lendingclub.com/browse/loanDetail.action?loan_id=1614412      1
https://lendingclub.com/browse/loanDetail.action?loan_id=19435976     1
https://lendingclub.com/browse/loanDetail.action?loan_id=44756872     1
https://lendingclub.com/browse/loanDetail.action?loan_id=108855699    1
https://lendingclub.com/browse/loanDetail.action?loan_id=68567951     1
https://lendingclub.com/browse/loanDetail.action?loan_id=60780727     1
https://lendingclub.com/browse/loanDetail.action?loan_id=110590636    1
https://lendingclub.com/browse/loanDetail.action?loan_id=26097620     1
https://lendingclub.com/browse/loanDetail.action?loan_id=10614687     1
https://lendingclub.com/browse/loanDetail.action?loan_id=74765207     1
https://lendingclub.com/browse/loanDetail.action?loan_id=111846656    1
https://lendingclub.com/browse/loanDetail.action?loan_id=73943819     1
https://lendingclub.com/browse/loanDetail.action?loan_id=40441134     1
https://lendingclub.com/browse/loanDetail.action?loan_id=7678610      1
https://lendingclub.com/browse/loanDetail.action?loan_id=78118784     1
https://lendingclub.com/browse/loanDetail.action?loan_id=88594709     1
https://lendingclub.com/browse/loanDetail.action?loan_id=17595490     1
https://lendingclub.com/browse/loanDetail.action?loan_id=25207860     1
https://lendingclub.com/browse/loanDetail.action?loan_id=67998215     1
https://lendingclub.com/browse/loanDetail.action?loan_id=111581583    1
https://lendingclub.com/browse/loanDetail.action?loan_id=119249601    1
https://lendingclub.com/browse/loanDetail.action?loan_id=75130721     1
https://lendingclub.com/browse/loanDetail.action?loan_id=104323458    1
https://lendingclub.com/browse/loanDetail.action?loan_id=112442611    1
https://lendingclub.com/browse/loanDetail.action?loan_id=60326720     1
https://lendingclub.com/browse/loanDetail.action?loan_id=13988278     1
https://lendingclub.com/browse/loanDetail.action?loan_id=76133237     1
https://lendingclub.com/browse/loanDetail.action?loan_id=63389426     1
https://lendingclub.com/browse/loanDetail.action?loan_id=61398615     1
https://lendingclub.com/browse/loanDetail.action?loan_id=577787       1
https://lendingclub.com/browse/loanDetail.action?loan_id=115396812    1
https://lendingclub.com/browse/loanDetail.action?loan_id=60893019     1
https://lendingclub.com/browse/loanDetail.action?loan_id=44775132     1
https://lendingclub.com/browse/loanDetail.action?loan_id=60821453     1
https://lendingclub.com/browse/loanDetail.action?loan_id=128745065    1
https://lendingclub.com/browse/loanDetail.action?loan_id=54898952     1
https://lendingclub.com/browse/loanDetail.action?loan_id=105447144    1
https://lendingclub.com/browse/loanDetail.action?loan_id=77380448     1
https://lendingclub.com/browse/loanDetail.action?loan_id=69524917     1
https://lendingclub.com/browse/loanDetail.action?loan_id=65414371     1
https://lendingclub.com/browse/loanDetail.action?loan_id=87474778     1
https://lendingclub.com/browse/loanDetail.action?loan_id=135773032    1
https://lendingclub.com/browse/loanDetail.action?loan_id=46743197     1
https://lendingclub.com/browse/loanDetail.action?loan_id=2894715      1
https://lendingclub.com/browse/loanDetail.action?loan_id=52556852     1
https://lendingclub.com/browse/loanDetail.action?loan_id=64823169     1
https://lendingclub.com/browse/loanDetail.action?loan_id=32019495     1
https://lendingclub.com/browse/loanDetail.action?loan_id=57682950     1
Name: count, dtype: int64

desc
                                                                            44
  Borrower added on 02/19/14 > Debt consolidation<br>                        5
  Borrower added on 12/19/13 > Debt consolidation<br>                        3
  Borrower added on 08/15/13 > Debt Consolidation<br>                        3
  Borrower added on 02/25/14 > Debt consolidation.<br>                       3
  Borrower added on 01/02/13 > Debt Consolidation<br>                        3
Camping Membership                                                           3
  Borrower added on 12/09/13 > debt consolidation<br>                        3
  Borrower added on 08/01/13 > Debt consolidation<br>                        2
  Borrower added on 02/05/14 > Debt consolidation<br>                        2
  Borrower added on 10/23/13 > Debt consolidation<br>                        2
  Borrower added on 01/27/14 > Debt consolidation<br>                        2
  Borrower added on 02/06/14 > debt consolidation<br>                        2
  Borrower added on 06/21/13 > Debt consolidation<br>                        2
  Borrower added on 04/24/13 > Debt Consolidation<br>                        2
  Borrower added on 12/10/13 > Debt consolidation<br>                        2
  Borrower added on 01/29/14 > Debt consolidation<br>                        2
  Borrower added on 10/16/13 > pay off high interest credit cards<br>        2
  Borrower added on 06/05/12 > debt consolidation<br>                        2
  Borrower added on 04/22/13 > Debt Consolidation<br>                        2
  Borrower added on 04/02/13 > debt consolidation<br>                        2
  Borrower added on 11/21/13 > Debt Consolidation<br>                        2
  Borrower added on 05/28/13 > Debt consolidation<br>                        2
  Borrower added on 11/30/12 > Debt consolidation<br>                        2
  Borrower added on 01/24/14 > Credit card consolidation<br>                 2
  Borrower added on 09/30/13 > Debt consolidation<br>                        2
  Borrower added on 07/01/12 > Debt Consolidation<br>                        2
  Borrower added on 10/10/13 > Debt consolidation<br>                        2
Debt Consolidation                                                           2
  Borrower added on 01/22/14 > Debt consolidation<br>                        2
  Borrower added on 08/06/13 > Credit card consolidation<br>                 2
  Borrower added on 09/30/12 > Debt Consolidation<br>                        2
  Borrower added on 03/05/14 > Pay off credit cards<br>                      2
  Borrower added on 06/06/13 > Debt Consolidation<br>                        2
  Borrower added on 01/13/14 > debt consolidation<br>                        2
  Borrower added on 01/03/14 > Debt consolidation<br>                        2
  Borrower added on 03/26/13 > Credit Card Refinancing<br>                   2
  Borrower added on 03/18/14 > To pay off high interest credit cards<br>     2
  Borrower added on 11/07/13 > credit card consolidation<br>                 2
  Borrower added on 01/03/13 > Debt consolidation<br>                        2
  Borrower added on 11/19/13 > Debt consolidation<br>                        2
  Borrower added on 05/06/13 > Debt Consolidation<br>                        2
  Borrower added on 03/17/14 > Debt consolidation<br>                        2
  Borrower added on 11/07/13 > Debt consolidation<br>                        2
  Borrower added on 03/18/14 > Debt consolidation<br>                        2
  Borrower added on 12/04/13 > Debt consolidation<br>                        2
  Borrower added on 09/12/13 > Debt consolidation<br>                        2
  Borrower added on 11/05/13 > Debt Consolidation<br>                        2
  Borrower added on 02/27/14 > Debt consolidation<br>                        2
  Borrower added on 03/03/13 > Debt consolidation<br>                        2
Name: count, dtype: int64

purpose
debt_consolidation    155720
credit_card            59220
home_improvement       17514
other                  15538
major_purchase          5729
small_business          3182
medical                 3053
car                     2874
moving                  1862
vacation                1818
house                   1453
wedding                  431
renewable_energy         161
educational               60
Name: count, dtype: int64

title
Debt consolidation           131798
Credit card refinancing       50090
Home improvement              15030
Other                         13339
Major purchase                 4691
Debt Consolidation             3060
Medical expenses               2670
Business                       2409
Car financing                  2199
Vacation                       1600
Moving and relocation          1534
Home buying                    1167
Consolidation                  1111
debt consolidation             1005
Debt Consolidation Loan         783
Credit Card Consolidation       473
consolidation                   438
Personal Loan                   424
Home Improvement                363
Consolidation Loan              349
Credit Card Refinance           297
Credit Card Payoff              261
Consolidate                     228
Personal                        223
Loan                            222
Freedom                         172
Payoff                          154
consolidate                     151
payoff                          144
Debt                            144
Credit Card Loan                139
personal                        137
Credit Cards                    137
Credit Card                     134
personal loan                   132
Green loan                      131
home improvement                130
DEBT CONSOLIDATION              125
Debt Consolidation              116
Refinance                       111
credit card consolidation       109
Small Business Loan             108
Debt Free                       105
credit card payoff              105
My Loan                         102
loan                             95
debt                             95
freedom                          91
Wedding                          90
Wedding Loan                     90
Name: count, dtype: int64

zip_code
945xx    3073
750xx    2895
112xx    2687
606xx    2403
300xx    2350
331xx    2223
900xx    2183
070xx    2166
891xx    2165
770xx    2120
100xx    2092
330xx    1921
917xx    1916
104xx    1886
117xx    1866
852xx    1706
925xx    1630
926xx    1605
921xx    1596
913xx    1557
334xx    1531
956xx    1518
853xx    1428
481xx    1383
760xx    1365
113xx    1354
604xx    1344
021xx    1317
080xx    1313
928xx    1300
920xx    1294
301xx    1293
802xx    1281
600xx    1271
601xx    1269
773xx    1266
850xx    1246
980xx    1239
207xx    1218
774xx    1216
941xx    1209
782xx    1165
201xx    1159
923xx    1140
800xx    1124
951xx    1115
480xx    1106
554xx    1090
114xx    1076
902xx    1066
Name: count, dtype: int64

addr_state
CA    39631
TX    22166
NY    21872
FL    18980
IL    10199
NJ     9614
PA     8989
OH     8644
GA     8589
VA     7600
NC     7489
MI     7003
AZ     6559
MA     6289
MD     6128
CO     5968
WA     5812
MN     4741
IN     4367
MO     4323
NV     4119
TN     4090
CT     3835
WI     3612
OR     3305
SC     3298
AL     3289
LA     3078
KY     2577
OK     2452
KS     2253
AR     2056
UT     1971
NM     1464
HI     1373
NH     1295
MS     1277
RI     1186
WV      958
MT      770
DE      719
DC      682
NE      668
AK      630
WY      564
VT      550
SD      535
ME      378
ID      373
ND      292
Name: count, dtype: int64

earliest_cr_line
Aug-2001    1929
Sep-2003    1888
Aug-2002    1797
Sep-2004    1775
Oct-2001    1729
Aug-2000    1729
Aug-2003    1723
Sep-2002    1704
Oct-2002    1699
Oct-2003    1682
Oct-2000    1674
Nov-2000    1660
Aug-2004    1651
Sep-2000    1639
Nov-1999    1629
Oct-1999    1599
Jul-2003    1585
Sep-2005    1573
Nov-2001    1549
Oct-2004    1535
Aug-1999    1531
Sep-1999    1527
Aug-2005    1503
Jul-2001    1501
Sep-2001    1497
Nov-2003    1450
Mar-2001    1449
Jul-2002    1437
Nov-2004    1430
Dec-2001    1421
Aug-2006    1418
Dec-2000    1416
Nov-2002    1411
May-2003    1407
Mar-2004    1406
May-2001    1404
Dec-1999    1403
Jun-2001    1401
Jan-2001    1391
Jul-2004    1385
Sep-1998    1377
May-2002    1371
Mar-2002    1366
Mar-2003    1353
Jul-2000    1348
Feb-2000    1336
Jun-2000    1331
May-2004    1324
Mar-2000    1322
Oct-1998    1318
Name: count, dtype: int64

initial_list_status
w    156449
f    112166
Name: count, dtype: int64

last_pymnt_d
2018-08-01    8040
2018-03-01    7668
2018-10-01    7415
2018-07-01    7292
2018-06-01    6977
2019-02-01    6866
2017-03-01    6634
2018-05-01    6605
2018-01-01    6582
2017-08-01    6533
2017-10-01    6471
2018-11-01    6397
2018-04-01    6383
2019-01-01    6318
2018-09-01    6280
2018-02-01    6204
2017-11-01    6180
2017-06-01    5982
2017-07-01    5972
2017-05-01    5681
2018-12-01    5536
2017-09-01    5399
2017-12-01    5382
2017-04-01    5134
2017-01-01    5123
2017-02-01    4955
2016-12-01    4892
2016-10-01    4575
2016-09-01    4473
2016-11-01    4457
2016-08-01    4454
2016-07-01    4325
2016-03-01    4060
2016-06-01    3956
2019-03-01    3890
2016-05-01    3639
2016-04-01    3554
2016-02-01    3454
2015-10-01    3103
2015-12-01    3046
2016-01-01    2993
2015-07-01    2883
2015-09-01    2715
2015-08-01    2601
2015-11-01    2596
2015-06-01    2371
2015-05-01    2216
2015-03-01    2199
2015-04-01    2128
2015-02-01    1801
Name: count, dtype: int64

last_credit_pull_d
Mar-2019    93838
Feb-2019    14842
Jan-2019    12399
Jul-2018    10575
Oct-2016    10123
Oct-2018     9282
Dec-2018     8827
Aug-2018     8575
Nov-2018     8434
Sep-2018     6645
Feb-2017     5350
May-2018     5029
Apr-2018     4802
Mar-2018     4705
Jan-2018     4324
Oct-2017     4306
Feb-2018     4179
Nov-2017     3653
Dec-2017     3369
Aug-2017     3334
Sep-2017     3236
Jun-2017     3086
Jul-2017     2980
Mar-2017     2700
Apr-2017     2402
Jan-2017     2199
May-2017     1998
Jun-2018     1840
Dec-2016     1761
Nov-2016     1481
Jul-2016     1058
Apr-2016     1017
Aug-2016      969
Mar-2016      925
Feb-2016      874
May-2016      783
Jun-2016      783
Jan-2016      680
Dec-2015      638
Sep-2015      588
Oct-2015      587
Jul-2015      573
Nov-2015      532
Jun-2015      478
Aug-2015      476
Apr-2015      462
Jan-2015      426
Mar-2015      407
Sep-2016      395
May-2015      395
Name: count, dtype: int64

application_type
Individual    263481
Joint App       5134
Name: count, dtype: int64

verification_status_joint
Not Verified       3012
Source Verified    1208
Verified            873
Name: count, dtype: int64

sec_app_earliest_cr_line
Aug-2005    45
Sep-2006    43
Jun-2005    38
Mar-2004    36
Oct-2004    33
Aug-2004    33
Nov-2005    32
Aug-2006    32
Sep-2004    32
Mar-2006    31
Nov-2004    31
Nov-2006    29
Jul-2005    29
May-2005    29
Sep-2005    29
Jul-2006    29
Oct-2003    29
Jul-2007    27
Jul-2003    26
May-2006    26
Jun-2006    25
Apr-2004    25
Jan-2003    25
Jan-2005    24
Oct-2001    24
Jul-2004    24
Aug-2007    24
Dec-2000    24
Mar-2005    24
Oct-2006    24
Dec-2006    23
Oct-2005    23
Dec-2005    23
Apr-2006    23
Feb-2006    23
Sep-2002    22
Nov-2002    22
Dec-2004    22
Jul-2002    22
Jan-2004    22
Feb-2007    21
Nov-2003    21
Feb-2005    21
Apr-2005    21
Jun-2007    21
Jun-2003    20
Jan-2007    20
Sep-2000    20
Aug-2003    20
Feb-2008    20
Name: count, dtype: int64

hardship_flag
N    268615
Name: count, dtype: int64

hardship_type
INTEREST ONLY-3 MONTHS DEFERRAL    1130
Name: count, dtype: int64

hardship_reason
NATURAL_DISASTER         314
EXCESSIVE_OBLIGATIONS    214
UNEMPLOYMENT             201
MEDICAL                  148
INCOME_CURTAILMENT       112
REDUCED_HOURS             65
DIVORCE                   34
FAMILY_DEATH              25
DISABILITY                17
Name: count, dtype: int64

hardship_status
COMPLETED    734
BROKEN       396
Name: count, dtype: int64

hardship_start_date
Sep-2017    269
Oct-2017    148
Nov-2017     81
Jun-2017     75
May-2017     69
Aug-2017     54
Jan-2018     49
Dec-2017     49
Jul-2017     41
Feb-2018     37
Aug-2018     36
Jul-2018     31
Mar-2018     30
Apr-2018     30
Jun-2018     27
May-2018     25
Oct-2018     23
Nov-2018     21
Sep-2018     18
Dec-2018     11
Jan-2017      2
Feb-2017      2
Apr-2017      1
Mar-2017      1
Name: count, dtype: int64

hardship_end_date
Dec-2017    208
Nov-2017    154
Jan-2018    104
Aug-2017     74
Oct-2017     70
Sep-2017     61
Feb-2018     60
Mar-2018     51
Apr-2018     47
Oct-2018     37
Jun-2018     34
Sep-2018     34
Jul-2017     31
Aug-2018     30
May-2018     30
Nov-2018     23
Jul-2018     21
Dec-2018     19
Jan-2019     19
Feb-2019     10
Jun-2017      4
May-2017      4
Mar-2017      2
Mar-2019      2
Apr-2017      1
Name: count, dtype: int64

payment_plan_start_date
Oct-2017    200
Sep-2017    187
Nov-2017    111
Jun-2017     70
Jul-2017     62
Jan-2018     53
Dec-2017     52
Aug-2017     46
Aug-2018     43
May-2017     41
Feb-2018     40
Apr-2018     32
May-2018     29
Mar-2018     29
Jun-2018     26
Jul-2018     25
Dec-2018     22
Nov-2018     21
Oct-2018     18
Sep-2018     17
Feb-2017      3
Mar-2017      2
Jan-2019      1
Name: count, dtype: int64

hardship_loan_status

## Descriptive Statistics

In [ ]:
key_vars = ["funded_amnt", "int_rate", "installment", "annual_inc", "rar"]

loans[key_vars].describe().round(2)

In [ ]:
# Descriptive statistics for RAR target variable
print("RAR Descriptive Statistics:")
print(loans["rar"].describe().round(2))
print(f"Skewness: {loans['rar'].skew().round(4)}")
print(f"Kurtosis: {loans['rar'].kurt().round(4)}")

In [ ]:
# Identify highly skewed numeric features
numeric_cols = loans.select_dtypes(include="number").columns
skewness = loans[numeric_cols].skew().sort_values(ascending=False)
print("Top 10 Most Skewed Features:")
print(skewness.head(10))
print("\nFeatures with |skew| > 1:")
print(skewness[skewness.abs() > 1])



# Visualize top 10 most skewed numeric features
top10_skew = skewness.abs().sort_values(ascending=False).head(10).sort_values()

plt.figure(figsize=(9, 6))
top10_skew.plot(kind="barh", color="steelblue")
plt.axvline(x=1, color="red", linestyle="--", linewidth=1, label="Threshold (|skew| = 1)")
plt.title("Top 10 Most Skewed Numeric Features")
plt.xlabel("Absolute Skewness")
plt.ylabel("Feature")
plt.legend()
plt.tight_layout()
plt.show()

print(f"Total features with |skew| > 1: {skewness[skewness.abs() > 1].shape[0]}")

## Correlation Analysis

In [ ]:
# Correlation matrix
# Compute correlation of all numeric features with RAR
numeric_cols = loans.select_dtypes(include="number").columns
rar_corr = loans[numeric_cols].corr()["rar"].drop("rar").sort_values(ascending=False)

print("Top 10 Positively Correlated Features with RAR:")
print(rar_corr.head(10).round(4))

print("\nTop 10 Negatively Correlated Features with RAR:")
print(rar_corr.tail(10).round(4))

In [ ]:
# Heatmap
# Focus heatmap on top 10 features correlated with RAR
top_10 = rar_corr.head(10).index.tolist()
top_10.append("rar")

corr_matrix_focused = loans[top_10].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(
    corr_matrix_focused,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5
)
plt.title("Correlation Heatmap — Top 10 Features vs RAR")
plt.tight_layout()
plt.show()

In [ ]:
# Flagging high multicollinearity between features
# Identify feature pairs with correlation above 0.85
high_corr_pairs = []
corr_matrix_full = loans[numeric_cols].corr().abs()

for i in range(len(corr_matrix_full.columns)):
    for j in range(i+1, len(corr_matrix_full.columns)):
        if corr_matrix_full.iloc[i, j] > 0.85:
            high_corr_pairs.append({
                "Feature 1": corr_matrix_full.columns[i],
                "Feature 2": corr_matrix_full.columns[j],
                "Correlation": corr_matrix_full.iloc[i, j].round(4)
            })

high_corr_df = pd.DataFrame(high_corr_pairs).sort_values("Correlation", ascending=False)
print(f"Number of highly correlated feature pairs (|r| > 0.85): {len(high_corr_df)}")
print(high_corr_df.head(40))